import Foundation
import MLX
import MLXFastCore
import MLXNN
import MLXLMCommon

/// Gemma 4 rotary position embedding kernels generated by MetalTile
/// (https://github.com/0xClandestine/metaltile). Each kernel is specialized
/// at build time for one of the four (sliding/full) × (Q/K) configurations
/// that appear in Gemma 4 31B:
///
/// | Layer type | head_dim | rotary_pairs | head_dim_half | theta_base |
/// |------------|----------|--------------|---------------|------------|
/// | sliding    | 256      | 128          | 128           | 10 000     |
/// | full       | 512      | 64           | 256           | 1 000 000  |
///
/// Q (32 heads) and K (16 heads sliding, 4 heads full) use the same kernel —
/// only the dispatch grid differs. The kernel writes to every element of
/// `out`: rotated for `i < rotary_pairs`, passthrough for the unrotated
/// tail, so the host doesn't need a separate `qk.copy()` step.
///
/// The wrapping class transposes the input to the kernel's expected
/// [B, L, n_heads, head_dim] contiguous layout (one extra copy), dispatches
/// the kernel, and transposes the result back to the caller's
/// [B, n_heads, L, head_dim] strided layout (zero-copy).

// MARK: - Metal kernels

/// Sliding-window Q — head_dim=256, full RoPE, row_stride = 32*256 = 8192.
private let gemma4SlidingQPrefill = MLXFast.metalKernel(
    name: "gemma4_mt_sliding_q_partial_rope_prefill_bf16",
    inputNames: ["qk", "positions"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 256u;
        constexpr uint half_rotary = 128u;
        constexpr uint head_dim_half = 128u;
        constexpr uint row_stride = 8192u;
        constexpr float theta_base = 10000f;
        uint v_r = thread_position_in_grid.x;
        uint v_i = thread_position_in_grid.z;
        auto v3 = row_stride;
        auto v5 = head_dim;
        uint v_head = thread_position_in_grid.y;
        auto v6 = v_head * v5;
        auto v_head_base = ((v_r * v3) + v6);
        auto v_dim_lo = v_head_base + v_i;
        auto v9 = head_dim_half;
        auto v10 = v_head_base + v9;
        auto v_dim_hi = v10 + v_i;
        auto v12 = qk[v_dim_lo];
        float v_x_lo = static_cast<float>(v12);
        auto v14 = qk[v_dim_hi];
        float v_x_hi = static_cast<float>(v14);
        auto v16 = half_rotary;
        auto v17 = v16 > v_i;
        if (v17) {
            auto v21 = theta_base;
            auto v22 = log2(v21);
            float v_half_f = static_cast<float>(v16);
            auto v26 = positions[v_r];
            auto v_inv_freq = exp2((((-static_cast<float>(v_i)) * v22) / v_half_f));
            auto v_theta = (static_cast<float>(v26) * v_inv_freq);
            auto v_cos_t = cos(v_theta);
            auto v_sin_t = sin(v_theta);
            auto v32 = v_x_hi * v_sin_t;
            auto v35 = v_x_hi * v_cos_t;
            bfloat v37 = bfloat(((v_x_lo * v_cos_t) - v32));
            out[v_dim_lo] = bfloat(v37);
            bfloat v38 = bfloat(((v_x_lo * v_sin_t) + v35));
            out[v_dim_hi] = bfloat(v38);
        } else {
            bfloat v39 = bfloat(v_x_lo);
            out[v_dim_lo] = bfloat(v39);
            bfloat v40 = bfloat(v_x_hi);
            out[v_dim_hi] = bfloat(v40);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

/// Sliding-window K — head_dim=256, full RoPE, row_stride = 16*256 = 4096.
private let gemma4SlidingKPrefill = MLXFast.metalKernel(
    name: "gemma4_mt_sliding_k_partial_rope_prefill_bf16",
    inputNames: ["qk", "positions"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 256u;
        constexpr uint half_rotary = 128u;
        constexpr uint head_dim_half = 128u;
        constexpr uint row_stride = 4096u;
        constexpr float theta_base = 10000f;
        uint v_r = thread_position_in_grid.x;
        uint v_i = thread_position_in_grid.z;
        auto v3 = row_stride;
        auto v5 = head_dim;
        uint v_head = thread_position_in_grid.y;
        auto v6 = v_head * v5;
        auto v_head_base = ((v_r * v3) + v6);
        auto v_dim_lo = v_head_base + v_i;
        auto v9 = head_dim_half;
        auto v10 = v_head_base + v9;
        auto v_dim_hi = v10 + v_i;
        auto v12 = qk[v_dim_lo];
        float v_x_lo = static_cast<float>(v12);
        auto v14 = qk[v_dim_hi];
        float v_x_hi = static_cast<float>(v14);
        auto v16 = half_rotary;
        auto v17 = v16 > v_i;
        if (v17) {
            auto v21 = theta_base;
            auto v22 = log2(v21);
            float v_half_f = static_cast<float>(v16);
            auto v26 = positions[v_r];
            auto v_inv_freq = exp2((((-static_cast<float>(v_i)) * v22) / v_half_f));
            auto v_theta = (static_cast<float>(v26) * v_inv_freq);
            auto v_cos_t = cos(v_theta);
            auto v_sin_t = sin(v_theta);
            auto v32 = v_x_hi * v_sin_t;
            auto v35 = v_x_hi * v_cos_t;
            bfloat v37 = bfloat(((v_x_lo * v_cos_t) - v32));
            out[v_dim_lo] = bfloat(v37);
            bfloat v38 = bfloat(((v_x_lo * v_sin_t) + v35));
            out[v_dim_hi] = bfloat(v38);
        } else {
            bfloat v39 = bfloat(v_x_lo);
            out[v_dim_lo] = bfloat(v39);
            bfloat v40 = bfloat(v_x_hi);
            out[v_dim_hi] = bfloat(v40);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

/// Full-attention Q — head_dim=512, partial RoPE (rotaryPairs=64), row_stride = 32*512 = 16384.
private let gemma4FullQPrefill = MLXFast.metalKernel(
    name: "gemma4_mt_full_q_partial_rope_prefill_bf16",
    inputNames: ["qk", "positions"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 512u;
        constexpr uint half_rotary = 64u;
        constexpr uint head_dim_half = 256u;
        constexpr uint row_stride = 16384u;
        constexpr float theta_base = 1000000f;
        uint v_r = thread_position_in_grid.x;
        uint v_i = thread_position_in_grid.z;
        auto v3 = row_stride;
        auto v5 = head_dim;
        uint v_head = thread_position_in_grid.y;
        auto v6 = v_head * v5;
        auto v_head_base = ((v_r * v3) + v6);
        auto v_dim_lo = v_head_base + v_i;
        auto v9 = head_dim_half;
        auto v10 = v_head_base + v9;
        auto v_dim_hi = v10 + v_i;
        auto v12 = qk[v_dim_lo];
        float v_x_lo = static_cast<float>(v12);
        auto v14 = qk[v_dim_hi];
        float v_x_hi = static_cast<float>(v14);
        auto v16 = half_rotary;
        auto v17 = v16 > v_i;
        if (v17) {
            auto v21 = theta_base;
            auto v22 = log2(v21);
            float v_half_f = static_cast<float>(v16);
            auto v26 = positions[v_r];
            auto v_inv_freq = exp2((((-static_cast<float>(v_i)) * v22) / v_half_f));
            auto v_theta = (static_cast<float>(v26) * v_inv_freq);
            auto v_cos_t = cos(v_theta);
            auto v_sin_t = sin(v_theta);
            auto v32 = v_x_hi * v_sin_t;
            auto v35 = v_x_hi * v_cos_t;
            bfloat v37 = bfloat(((v_x_lo * v_cos_t) - v32));
            out[v_dim_lo] = bfloat(v37);
            bfloat v38 = bfloat(((v_x_lo * v_sin_t) + v35));
            out[v_dim_hi] = bfloat(v38);
        } else {
            bfloat v39 = bfloat(v_x_lo);
            out[v_dim_lo] = bfloat(v39);
            bfloat v40 = bfloat(v_x_hi);
            out[v_dim_hi] = bfloat(v40);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

/// Full-attention K — head_dim=512, partial RoPE (rotaryPairs=64), row_stride = 4*512 = 2048.
private let gemma4FullKPrefill = MLXFast.metalKernel(
    name: "gemma4_mt_full_k_partial_rope_prefill_bf16",
    inputNames: ["qk", "positions"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 512u;
        constexpr uint half_rotary = 64u;
        constexpr uint head_dim_half = 256u;
        constexpr uint row_stride = 2048u;
        constexpr float theta_base = 1000000f;
        uint v_r = thread_position_in_grid.x;
        uint v_i = thread_position_in_grid.z;
        auto v3 = row_stride;
        auto v5 = head_dim;
        uint v_head = thread_position_in_grid.y;
        auto v6 = v_head * v5;
        auto v_head_base = ((v_r * v3) + v6);
        auto v_dim_lo = v_head_base + v_i;
        auto v9 = head_dim_half;
        auto v10 = v_head_base + v9;
        auto v_dim_hi = v10 + v_i;
        auto v12 = qk[v_dim_lo];
        float v_x_lo = static_cast<float>(v12);
        auto v14 = qk[v_dim_hi];
        float v_x_hi = static_cast<float>(v14);
        auto v16 = half_rotary;
        auto v17 = v16 > v_i;
        if (v17) {
            auto v21 = theta_base;
            auto v22 = log2(v21);
            float v_half_f = static_cast<float>(v16);
            auto v26 = positions[v_r];
            auto v_inv_freq = exp2((((-static_cast<float>(v_i)) * v22) / v_half_f));
            auto v_theta = (static_cast<float>(v26) * v_inv_freq);
            auto v_cos_t = cos(v_theta);
            auto v_sin_t = sin(v_theta);
            auto v32 = v_x_hi * v_sin_t;
            auto v35 = v_x_hi * v_cos_t;
            bfloat v37 = bfloat(((v_x_lo * v_cos_t) - v32));
            out[v_dim_lo] = bfloat(v37);
            bfloat v38 = bfloat(((v_x_lo * v_sin_t) + v35));
            out[v_dim_hi] = bfloat(v38);
        } else {
            bfloat v39 = bfloat(v_x_lo);
            out[v_dim_lo] = bfloat(v39);
            bfloat v40 = bfloat(v_x_hi);
            out[v_dim_hi] = bfloat(v40);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

// MARK: - Dispatcher

private func gemma4PickRopeKernel(headDim: Int, nHeads: Int) -> MLXFast.MLXFastKernel {
    switch (headDim, nHeads) {
    case (256, 32): return gemma4SlidingQPrefill
    case (256, 16): return gemma4SlidingKPrefill
    case (512, 32): return gemma4FullQPrefill
    case (512, 4):  return gemma4FullKPrefill
    default:
        fatalError(
            "gemma4_mt partial RoPE: unsupported (head_dim=\(headDim), n_heads=\(nHeads)) — expected (256, 32|16) or (512, 32|4)"
        )
    }
}

private func gemma4PickHeadDimHalf(headDim: Int) -> Int {
    headDim / 2
}

// MARK: - Public RoPE layer

public final class Gemma4PartialRoPEMetalTile: Module, OffsetLayer, ArrayOffsetLayer {
    public let dims: Int
    public let traditional: Bool = false

    public init(dims: Int) {
        self.dims = dims
        super.init()
    }

    public func callAsFunction(_ x: MLXArray, offset: Int = 0) -> MLXArray {
        precondition(x.ndim == 4, "gemma4_mt RoPE: expected 4D input, got \(x.ndim)D")
        precondition(x.dtype == .bfloat16, "gemma4_mt RoPE: expected bf16 input, got \(x.dtype)")
        let nHeads = x.shape[1]
        let L = x.shape[2]
        let headDim = x.shape[3]
        precondition(headDim == dims, "gemma4_mt RoPE: head_dim mismatch (\(headDim) vs \(dims))")
        precondition(headDim == 256 || headDim == 512, "gemma4_mt RoPE: unsupported head_dim=\(headDim)")

        let contiguousIn = x.transposed(0, 2, 1, 3).contiguous()
        precondition(headDim == dims, "gemma4_mt RoPE: head_dim mismatch (\(headDim) vs \(dims))")
        precondition(headDim == 256 || headDim == 512, "gemma4_mt RoPE: unsupported head_dim=\(headDim)")

        let positions = gemma4BuildPositions(start: UInt32(offset), length: L)

        let out = gemma4DispatchPrefill(
            input: contiguousIn,
            positions: positions,
            nHeads: nHeads,
            headDim: headDim
        )

        return out.transposed(0, 2, 1, 3)
    }

    public func callAsFunction(_ x: MLXArray, offset: MLXArray) -> MLXArray {
        precondition(x.ndim == 4, "gemma4_mt RoPE: expected 4D input, got \(x.ndim)D")
        precondition(x.dtype == .bfloat16, "gemma4_mt RoPE: expected bf16 input, got \(x.dtype)")
        let nHeads = x.shape[1]
        let L = x.shape[2]
        let headDim = x.shape[3]
        precondition(headDim == dims, "gemma4_mt RoPE: head_dim mismatch (\(headDim) vs \(dims))")
        precondition(headDim == 256 || headDim == 512, "gemma4_mt RoPE: unsupported head_dim=\(headDim)")
        precondition(offset.size == L, "gemma4_mt RoPE: offset.size (\(offset.size)) must equal L (\(L))")

        let contiguousIn = x.transposed(0, 2, 1, 3).contiguous()
        precondition(headDim == dims, "gemma4_mt RoPE: head_dim mismatch (\(headDim) vs \(dims))")
        precondition(headDim == 256 || headDim == 512, "gemma4_mt RoPE: unsupported head_dim=\(headDim)")
        precondition(offset.size == L, "gemma4_mt RoPE: offset.size (\(offset.size)) must equal L (\(L))")

        let positions: MLXArray
        if offset.ndim == 0 {
            let start = offset.item(UInt32.self)
            positions = gemma4BuildPositions(start: start, length: L)
        } else {
            positions = offset.asType(.uint32)
        }

        let out = gemma4DispatchPrefill(
            input: contiguousIn,
            positions: positions,
            nHeads: nHeads,
            headDim: headDim
        )

        return out.transposed(0, 2, 1, 3)
    }
}



private func gemma4DispatchPrefill(
    input: MLXArray,
    positions: MLXArray,
    nHeads: Int,
    headDim: Int
) -> MLXArray {
    let L = input.shape[1]
    let headDimHalf = gemma4PickHeadDimHalf(headDim: headDim)
    let kernel = gemma4PickRopeKernel(headDim: headDim, nHeads: nHeads)

    return kernel(
        [input, positions],
        grid: (L, nHeads, headDimHalf),
        threadGroup: (1, 1, 1),
        outputShapes: [input.shape],
        outputDTypes: [.bfloat16]
    )[0]
}

private func gemma4BuildPositions(start: UInt32, length: Int) -> MLXArray {
    var data = [UInt32](repeating: 0, count: length)
    for i in 0..<length {
        data[i] = start &+ UInt32(i)
    }
    return data.withUnsafeBufferPointer { ptr in
        MLXArray(
            UnsafeRawBufferPointer(ptr),
            [length],
            type: UInt32.self
        )
    }
}
