import Foundation
import MLX
import MLXFastCore
import MLXNN
import MLXLMCommon

/// Gemma 4 fused RMSNorm + RoPE kernels (prefill variant).
///
/// One threadgroup per (batch, sequence_position, head) row. Threads
/// = `head_dim_half` (one per rotation pair). Phase 1: per-thread
/// partial sum-of-squares (one pair per thread) → threadgroup reduce →
/// inv_rms. Phase 2: load RMS weight, normalize, apply NEOX-pair
/// RoPE rotation. The kernel writes BOTH rotated pairs (i in
/// `[0, half_rotary)`) and unrotated tail (i in `[half_rotary,
/// head_dim_half)`) directly into `out` — no intermediate tensor.
///
/// Replaces the `MLXFast.rmsNorm` + `MLXFast.RoPE` chain in the simple
/// prefill Q/K path with a single dispatch, saving 1 launch + 1 read +
/// 1 write of the Q/K tensor per Q and per K per layer.
///
/// MSL generated by MetalTile (https://github.com/0xClandestine/metaltile)
/// from `gemma4_fused_rms_norm_rope_prefill<T>` in our small kernel
/// crate. Specialized at Swift-compile time for the four (sliding/full)
/// × (Q/K) shapes that appear in Gemma 4 31B (head_dim ∈ {256, 512},
/// rotaryPairs ∈ {128, 64}, theta_base ∈ {10 000, 1 000 000}).

// MARK: - Metal kernels

/// Sliding-window Q — head_dim=256, full RoPE (rotaryPairs=128), theta=10000.
private let gemma4FusedSlidingQ = MLXFast.metalKernel(
    name: "gemma4_mt_fused_rms_norm_rope_sliding_q_bf16",
    inputNames: ["x", "weight", "positions", "eps_buf"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 256u;
        constexpr uint head_dim_half = 128u;
        constexpr uint half_rotary = 128u;
        constexpr float theta_base = 10000f;
        uint tgid_x = _tgid3.x;
        uint tgid_y = _tgid3.y;
        uint lsize  = _lsize3.x;
        uint n_simd = lsize / 32u;
        if (n_simd == 0u) { return; }
        threadgroup float v56_sg[32];

        uint v_row = tgid_x;
        uint v_lid = tgid_y;
        auto v2 = head_dim;
        auto v_rs = v_row * v2;
        auto v4 = v_rs + v_lid;
        auto v5 = x[v4];
        float v_x_lo = static_cast<float>(v5);
        auto v8 = head_dim_half;
        auto v9 = v4 + v8;
        auto v10 = x[v9];
        float v_x_hi = static_cast<float>(v10);
        auto v13 = v_x_hi * v_x_hi;
        auto v_partial_ssq = ((v_x_lo * v_x_lo) + v13);
        float v56;
        {
            float _sv = simd_sum(float(v_partial_ssq));
            if (simd_lane == 0) v56_sg[simd_group] = _sv;
            threadgroup_barrier(mem_flags::mem_threadgroup);
            if (simd_group == 0) {
                float _wv = simd_lane < n_simd ? v56_sg[simd_lane] : 0.0f;
                v56_sg[0] = simd_sum(_wv);
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            v56 = v56_sg[0];
        }
        auto v57 = eps_buf[0];
        auto v58 = head_dim;
        auto v_inv_rms = rsqrt(((v56 / v58) + v57));
        auto v_pos = positions[v_row];
        auto v18 = half_rotary;
        auto v22 = theta_base;
        auto v23 = log2(v22);
        float v_half_f = static_cast<float>(v18);
        auto v_inv_freq = exp2((((-static_cast<float>(v_lid)) * v23) / v_half_f));
        auto v_theta = (static_cast<float>(v_pos) * v_inv_freq);
        auto v_cos_t = cos(v_theta);
        auto v_sin_t = sin(v_theta);
        auto v30 = weight[v_lid];
        float v_w_lo = static_cast<float>(v30);
        auto v32 = v_lid + v8;
        auto v33 = weight[v32];
        float v_w_hi = static_cast<float>(v33);
        auto v_normed_lo = v_x_lo * v_w_lo * v_inv_rms;
        auto v_normed_hi = v_x_hi * v_w_hi * v_inv_rms;
        if (v18 > v_lid) {
            auto v_o_lo = v_normed_lo * v_cos_t - v_normed_hi * v_sin_t;
            auto v_o_hi = v_normed_lo * v_sin_t + v_normed_hi * v_cos_t;
            out[v4] = static_cast<bfloat>(v_o_lo);
            out[v9] = static_cast<bfloat>(v_o_hi);
        } else {
            out[v4] = static_cast<bfloat>(v_normed_lo);
            out[v9] = static_cast<bfloat>(v_normed_hi);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

/// Sliding-window K — head_dim=256, full RoPE (rotaryPairs=128), theta=10000.
private let gemma4FusedSlidingK = MLXFast.metalKernel(
    name: "gemma4_mt_fused_rms_norm_rope_sliding_k_bf16",
    inputNames: ["x", "weight", "positions", "eps_buf"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 256u;
        constexpr uint head_dim_half = 128u;
        constexpr uint half_rotary = 128u;
        constexpr float theta_base = 10000f;
        uint tgid_x = _tgid3.x;
        uint tgid_y = _tgid3.y;
        uint lsize  = _lsize3.x;
        uint n_simd = lsize / 32u;
        if (n_simd == 0u) { return; }
        threadgroup float v56_sg[32];

        uint v_row = tgid_x;
        uint v_lid = tgid_y;
        auto v2 = head_dim;
        auto v_rs = v_row * v2;
        auto v4 = v_rs + v_lid;
        auto v5 = x[v4];
        float v_x_lo = static_cast<float>(v5);
        auto v8 = head_dim_half;
        auto v9 = v4 + v8;
        auto v10 = x[v9];
        float v_x_hi = static_cast<float>(v10);
        auto v13 = v_x_hi * v_x_hi;
        auto v_partial_ssq = ((v_x_lo * v_x_lo) + v13);
        float v56;
        {
            float _sv = simd_sum(float(v_partial_ssq));
            if (simd_lane == 0) v56_sg[simd_group] = _sv;
            threadgroup_barrier(mem_flags::mem_threadgroup);
            if (simd_group == 0) {
                float _wv = simd_lane < n_simd ? v56_sg[simd_lane] : 0.0f;
                v56_sg[0] = simd_sum(_wv);
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            v56 = v56_sg[0];
        }
        auto v57 = eps_buf[0];
        auto v58 = head_dim;
        auto v_inv_rms = rsqrt(((v56 / v58) + v57));
        auto v_pos = positions[v_row];
        auto v18 = half_rotary;
        auto v22 = theta_base;
        auto v23 = log2(v22);
        float v_half_f = static_cast<float>(v18);
        auto v_inv_freq = exp2((((-static_cast<float>(v_lid)) * v23) / v_half_f));
        auto v_theta = (static_cast<float>(v_pos) * v_inv_freq);
        auto v_cos_t = cos(v_theta);
        auto v_sin_t = sin(v_theta);
        auto v30 = weight[v_lid];
        float v_w_lo = static_cast<float>(v30);
        auto v32 = v_lid + v8;
        auto v33 = weight[v32];
        float v_w_hi = static_cast<float>(v33);
        auto v_normed_lo = v_x_lo * v_w_lo * v_inv_rms;
        auto v_normed_hi = v_x_hi * v_w_hi * v_inv_rms;
        if (v18 > v_lid) {
            auto v_o_lo = v_normed_lo * v_cos_t - v_normed_hi * v_sin_t;
            auto v_o_hi = v_normed_lo * v_sin_t + v_normed_hi * v_cos_t;
            out[v4] = static_cast<bfloat>(v_o_lo);
            out[v9] = static_cast<bfloat>(v_o_hi);
        } else {
            out[v4] = static_cast<bfloat>(v_normed_lo);
            out[v9] = static_cast<bfloat>(v_normed_hi);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

/// Full-attention Q — head_dim=512, partial RoPE (rotaryPairs=64), theta=1e6.
private let gemma4FusedFullQ = MLXFast.metalKernel(
    name: "gemma4_mt_fused_rms_norm_rope_full_q_bf16",
    inputNames: ["x", "weight", "positions", "eps_buf"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 512u;
        constexpr uint head_dim_half = 256u;
        constexpr uint half_rotary = 64u;
        constexpr float theta_base = 1000000f;
        uint tgid_x = _tgid3.x;
        uint tgid_y = _tgid3.y;
        uint lsize  = _lsize3.x;
        uint n_simd = lsize / 32u;
        if (n_simd == 0u) { return; }
        threadgroup float v56_sg[32];

        uint v_row = tgid_x;
        uint v_lid = tgid_y;
        auto v2 = head_dim;
        auto v_rs = v_row * v2;
        auto v4 = v_rs + v_lid;
        auto v5 = x[v4];
        float v_x_lo = static_cast<float>(v5);
        auto v8 = head_dim_half;
        auto v9 = v4 + v8;
        auto v10 = x[v9];
        float v_x_hi = static_cast<float>(v10);
        auto v13 = v_x_hi * v_x_hi;
        auto v_partial_ssq = ((v_x_lo * v_x_lo) + v13);
        float v56;
        {
            float _sv = simd_sum(float(v_partial_ssq));
            if (simd_lane == 0) v56_sg[simd_group] = _sv;
            threadgroup_barrier(mem_flags::mem_threadgroup);
            if (simd_group == 0) {
                float _wv = simd_lane < n_simd ? v56_sg[simd_lane] : 0.0f;
                v56_sg[0] = simd_sum(_wv);
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            v56 = v56_sg[0];
        }
        auto v57 = eps_buf[0];
        auto v58 = head_dim;
        auto v_inv_rms = rsqrt(((v56 / v58) + v57));
        auto v_pos = positions[v_row];
        auto v18 = half_rotary;
        auto v22 = theta_base;
        auto v23 = log2(v22);
        float v_half_f = static_cast<float>(v18);
        auto v_inv_freq = exp2((((-static_cast<float>(v_lid)) * v23) / v_half_f));
        auto v_theta = (static_cast<float>(v_pos) * v_inv_freq);
        auto v_cos_t = cos(v_theta);
        auto v_sin_t = sin(v_theta);
        auto v30 = weight[v_lid];
        float v_w_lo = static_cast<float>(v30);
        auto v32 = v_lid + v8;
        auto v33 = weight[v32];
        float v_w_hi = static_cast<float>(v33);
        auto v_normed_lo = v_x_lo * v_w_lo * v_inv_rms;
        auto v_normed_hi = v_x_hi * v_w_hi * v_inv_rms;
        if (v18 > v_lid) {
            auto v_o_lo = v_normed_lo * v_cos_t - v_normed_hi * v_sin_t;
            auto v_o_hi = v_normed_lo * v_sin_t + v_normed_hi * v_cos_t;
            out[v4] = static_cast<bfloat>(v_o_lo);
            out[v9] = static_cast<bfloat>(v_o_hi);
        } else {
            out[v4] = static_cast<bfloat>(v_normed_lo);
            out[v9] = static_cast<bfloat>(v_normed_hi);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

/// Full-attention K — head_dim=512, partial RoPE (rotaryPairs=64), theta=1e6.
private let gemma4FusedFullK = MLXFast.metalKernel(
    name: "gemma4_mt_fused_rms_norm_rope_full_k_bf16",
    inputNames: ["x", "weight", "positions", "eps_buf"],
    outputNames: ["out"],
    source: """
        constexpr uint head_dim = 512u;
        constexpr uint head_dim_half = 256u;
        constexpr uint half_rotary = 64u;
        constexpr float theta_base = 1000000f;
        uint tgid_x = _tgid3.x;
        uint tgid_y = _tgid3.y;
        uint lsize  = _lsize3.x;
        uint n_simd = lsize / 32u;
        if (n_simd == 0u) { return; }
        threadgroup float v56_sg[32];

        uint v_row = tgid_x;
        uint v_lid = tgid_y;
        auto v2 = head_dim;
        auto v_rs = v_row * v2;
        auto v4 = v_rs + v_lid;
        auto v5 = x[v4];
        float v_x_lo = static_cast<float>(v5);
        auto v8 = head_dim_half;
        auto v9 = v4 + v8;
        auto v10 = x[v9];
        float v_x_hi = static_cast<float>(v10);
        auto v13 = v_x_hi * v_x_hi;
        auto v_partial_ssq = ((v_x_lo * v_x_lo) + v13);
        float v56;
        {
            float _sv = simd_sum(float(v_partial_ssq));
            if (simd_lane == 0) v56_sg[simd_group] = _sv;
            threadgroup_barrier(mem_flags::mem_threadgroup);
            if (simd_group == 0) {
                float _wv = simd_lane < n_simd ? v56_sg[simd_lane] : 0.0f;
                v56_sg[0] = simd_sum(_wv);
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
            v56 = v56_sg[0];
        }
        auto v57 = eps_buf[0];
        auto v58 = head_dim;
        auto v_inv_rms = rsqrt(((v56 / v58) + v57));
        auto v_pos = positions[v_row];
        auto v18 = half_rotary;
        auto v22 = theta_base;
        auto v23 = log2(v22);
        float v_half_f = static_cast<float>(v18);
        auto v_inv_freq = exp2((((-static_cast<float>(v_lid)) * v23) / v_half_f));
        auto v_theta = (static_cast<float>(v_pos) * v_inv_freq);
        auto v_cos_t = cos(v_theta);
        auto v_sin_t = sin(v_theta);
        auto v30 = weight[v_lid];
        float v_w_lo = static_cast<float>(v30);
        auto v32 = v_lid + v8;
        auto v33 = weight[v32];
        float v_w_hi = static_cast<float>(v33);
        auto v_normed_lo = v_x_lo * v_w_lo * v_inv_rms;
        auto v_normed_hi = v_x_hi * v_w_hi * v_inv_rms;
        if (v18 > v_lid) {
            auto v_o_lo = v_normed_lo * v_cos_t - v_normed_hi * v_sin_t;
            auto v_o_hi = v_normed_lo * v_sin_t + v_normed_hi * v_cos_t;
            out[v4] = static_cast<bfloat>(v_o_lo);
            out[v9] = static_cast<bfloat>(v_o_hi);
        } else {
            out[v4] = static_cast<bfloat>(v_normed_lo);
            out[v9] = static_cast<bfloat>(v_normed_hi);
        }
        """,
    header: "using namespace metal;",
    ensureRowContiguous: true
)

// MARK: - Dispatcher

/// Pick the right kernel for the given (head_dim, layer type).
private func gemma4FusedPickKernel(
    headDim: Int,
    isSliding: Bool
) -> MLXFast.MLXFastKernel {
    switch (headDim, isSliding) {
    case (256, true): return gemma4FusedSlidingQ  // head_dim is 256 for Q or K
    case (256, false): return gemma4FusedFullQ
    case (512, true): return gemma4FusedFullQ     // shouldn't happen — sliding is always D=256
    case (512, false): return gemma4FusedFullQ
    default:
        // Use full Q/K as a fallback — wrong shape will fail at runtime
        return headDim == 256 ? gemma4FusedSlidingK : gemma4FusedFullK
    }
}

/// Same kernel for Q and K (we'd ideally differentiate to keep the
/// specializations tight, but the kernel itself is head_dim-dispatched
/// and the Q/K specialization in the partial-RoPE kernel was only a
/// per-row_stride difference — fused kernels do not need per-role
/// constexprs since each row is one head).
///
/// Threadgroup geometry: one TG per row, threads = `head_dim_half`.
/// Grid: `[B*L*n_heads, 1, 1]`, threadGroup: `[head_dim_half, 1, 1]`.
public enum Gemma4FusedRMSNormRoPE {
    /// Apply fused RMSNorm + NEOX partial RoPE to a [B, L, n_heads,
    /// head_dim] contiguous tensor. Returns a new tensor of the same
    /// shape and layout. Pass `positions: [B*L]` (u32) for the
    /// per-row position; pass `eps: f32` for the RMS epsilon.
    public static func apply(
        x: MLXArray,
        weight: MLXArray,
        positions: MLXArray,
        eps: Float,
        headDim: Int,
        isSliding: Bool
    ) -> MLXArray {
        precondition(x.ndim == 4, "expected 4D input, got \(x.ndim)D")
        precondition(x.dtype == .bfloat16, "expected bf16 input, got \(x.dtype)")
        precondition(weight.ndim == 1, "expected 1D weight, got \(weight.ndim)D")
        precondition(weight.size == headDim, "weight size (\(weight.size)) must equal headDim (\(headDim))")
        precondition(x.shape[3] == headDim, "last dim (\(x.shape[3])) must equal headDim (\(headDim))")
        precondition(headDim == 256 || headDim == 512, "unsupported head_dim=\(headDim)")

        let B = x.shape[0]
        let L = x.shape[1]
        let nHeads = x.shape[2]
        let rows = B * L * nHeads

        // Flatten [B, L, n_heads, head_dim] -> [rows, head_dim] (no copy:
        // reshape is a view change for the contiguous tensor).
        let flat = x.reshaped([rows, headDim])

        let halfDimHalf: Int
        switch headDim {
        case 256: halfDimHalf = 128
        case 512: halfDimHalf = 256
        default: fatalError("unreachable")
        }

        let epsData = [eps]
        let epsBuf: MLXArray = epsData.withUnsafeBufferPointer { ptr in
            MLXArray(
                UnsafeRawBufferPointer(ptr),
                [1],
                type: Float.self
            )
        }

        let kernel = gemma4FusedPickKernel(headDim: headDim, isSliding: isSliding)

        return kernel(
            [flat, weight, positions, epsBuf],
            grid: (rows, halfDimHalf, 1),
            threadGroup: (halfDimHalf, 1, 1),
            outputShapes: [flat.shape],
            outputDTypes: [.bfloat16]
        )[0]
    }
}

/// Build a length-`length` u32 positions array `[start, start+1, …, start+length-1]`.
public func gemma4BuildFusedPositions(start: Int, length: Int) -> MLXArray {
    var data = [UInt32](repeating: 0, count: length)
    for i in 0..<length {
        data[i] = UInt32(start + i)
    }
    return data.withUnsafeBufferPointer { ptr in
        MLXArray(
            UnsafeRawBufferPointer(ptr),
            [length],
            type: UInt32.self
        )
    }
}
