import MLX

/// Indexed affine QMV for the attention output projection.  The stock
/// quantized matmul is particularly expensive for decode's one-row input;
/// this path reuses the compact scale/bias LUT generated by the transform.
private func makeGemma4IndexedOutputKernel(inputWidth: Int) -> MLXFast.MLXFastKernel {
    let groups = inputWidth / 64
    let bytesPerRow = inputWidth / 2
    let blocks = inputWidth / 256
    return MLXFast.metalKernel(
        name: "gemma4_indexed_o_proj_\(inputWidth)_v1",
        inputNames: ["weight", "indices", "lut", "x"],
        outputNames: ["output"],
        source: """
            constexpr int kInputWidth = \(inputWidth);
            constexpr int kGroupsPerRow = \(groups);
            constexpr int kWeightBytesPerRow = \(bytesPerRow);
            constexpr int kBlocks = \(blocks);
            constexpr int kRowsPerSIMD = 4;

            const int output_row = threadgroup_position_in_grid.y * 4;
            const device uchar* weight_bytes =
                reinterpret_cast<const device uchar*>(weight)
                + output_row * kWeightBytesPerRow
                + thread_index_in_simdgroup * 4;
            const device ushort* row_indices =
                indices + output_row * kGroupsPerRow
                + thread_index_in_simdgroup / 8;
            const device bfloat* input = x + thread_index_in_simdgroup * 8;

            float result[kRowsPerSIMD] = {0};
            for (int block = 0; block < kBlocks; ++block) {
                float values[8];
                const float input_sum = gemma4_indexed_output_load_values(input, values);
                for (int row = 0; row < kRowsPerSIMD; ++row) {
                    const device uchar* row_weight =
                        weight_bytes + row * kWeightBytesPerRow;
                    const ushort metadata_index = row_indices[row * kGroupsPerRow];
                    const uint pair = lut[metadata_index];
                    result[row] += gemma4_indexed_output_qdot(
                        row_weight,
                        values,
                        gemma4_indexed_output_pair_scale(pair),
                        gemma4_indexed_output_pair_bias(pair),
                        input_sum);
                }
                weight_bytes += 128;
                row_indices += 4;
                input += 256;
            }

            for (int row = 0; row < kRowsPerSIMD; ++row) {
                result[row] = simd_sum(result[row]);
                if (thread_index_in_simdgroup == 0) {
                    output[output_row + row] = static_cast<bfloat>(result[row]);
                }
            }
            """,
        header: """
            using namespace metal;

            inline float gemma4_indexed_output_pair_scale(uint pair) {
                return static_cast<float>(as_type<bfloat>(static_cast<ushort>(pair)));
            }

            inline float gemma4_indexed_output_pair_bias(uint pair) {
                return static_cast<float>(
                    as_type<bfloat>(static_cast<ushort>(pair >> 16)));
            }

            inline float gemma4_indexed_output_load_values(
                const device bfloat* input,
                thread float* values
            ) {
                float sum = 0;
                for (int index = 0; index < 8; index += 4) {
                    sum += input[index] + input[index + 1]
                        + input[index + 2] + input[index + 3];
                    values[index] = input[index];
                    values[index + 1] = input[index + 1] / 16.0f;
                    values[index + 2] = input[index + 2] / 256.0f;
                    values[index + 3] = input[index + 3] / 4096.0f;
                }
                return sum;
            }

            inline float gemma4_indexed_output_qdot(
                const device uchar* weight,
                const thread float* values,
                float scale,
                float bias,
                float input_sum
            ) {
                const device ushort* packed =
                    reinterpret_cast<const device ushort*>(weight);
                float accumulator = 0;
                for (int index = 0; index < 2; ++index) {
                    accumulator +=
                        values[4 * index] * (packed[index] & 0x000f)
                        + values[4 * index + 1] * (packed[index] & 0x00f0)
                        + values[4 * index + 2] * (packed[index] & 0x0f00)
                        + values[4 * index + 3] * (packed[index] & 0xf000);
                }
                return scale * accumulator + input_sum * bias;
            }
            """,
        ensureRowContiguous: true
    )
}

private let gemma4IndexedOutputSliding = makeGemma4IndexedOutputKernel(inputWidth: 8_192)
private let gemma4IndexedOutputFull = makeGemma4IndexedOutputKernel(inputWidth: 16_384)

func supportsGemma4IndexedOutput(
    projection: FastQuantizedProjection,
    metadata: IndexedAffineMetadata,
    inputWidth: Int
) -> Bool {
    guard let biases = projection.biases else { return false }
    let groups = inputWidth / 64
    return projection.groupSize == 64
        && projection.bits == 4
        && projection.weight.dtype == .uint32
        && projection.weight.shape == [5_376, inputWidth / 8]
        && projection.scales.dtype == .bfloat16
        && projection.scales.shape == [5_376, groups]
        && biases.dtype == .bfloat16
        && biases.shape == [5_376, groups]
        && metadata.indices.dtype == .uint16
        && metadata.indices.shape == [5_376, groups]
        && metadata.lut.dtype == .uint32
        && metadata.lut.ndim == 1
        && (1...65_536).contains(metadata.lut.size)
}

struct IndexedOutputProjection: @unchecked Sendable {
    let projection: FastQuantizedProjection
    let metadata: IndexedAffineMetadata
    let inputWidth: Int

    init(
        projection: FastQuantizedProjection,
        metadata: IndexedAffineMetadata,
        inputWidth: Int
    ) {
        precondition(supportsGemma4IndexedOutput(
            projection: projection, metadata: metadata, inputWidth: inputWidth))
        self.projection = projection
        self.metadata = metadata
        self.inputWidth = inputWidth
    }

    func callAsFunction(_ input: MLXArray) -> MLXArray {
        precondition(input.dtype == .bfloat16)
        precondition(input.shape == [1, 1, inputWidth])
        let kernel = inputWidth == 8_192
            ? gemma4IndexedOutputSliding
            : gemma4IndexedOutputFull
        return kernel(
            [projection.weight, metadata.indices, metadata.lut, input],
            grid: (32, 1_344, 1),
            threadGroup: (32, 1, 1),
            outputShapes: [[1, 1, 5_376]],
            outputDTypes: [.bfloat16]
        )[0]
    }
}
